AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Template for creating a Lambda based ML API
Globals:
  Function:
    Runtime: python2.7
    MemorySize: 3008
    Timeout: 300
    Environment:
      # Expose Cloudformation Stack name as STACK_NAME environment variable for Lambda process
      Variables:
        STACK_NAME: !Ref AWS::StackName
    Tags:
      project: ml-engineer
Resources:
  LambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub '${AWS::StackName}-lambda-role'
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3ReadWrite
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !Sub 'arn:aws:s3:::${S3Bucket}/*'
                  - !Sub 'arn:aws:s3:::${S3Bucket}'
                  - 'arn:aws:s3:::ml-engineer/*'
                  - 'arn:aws:s3:::ml-engineer'
  TrainLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: 'Trains a ML model'
      Handler: train.lambda_handler
      CodeUri: 's3://ml-engineer/cloudformation/lambda_templates/train.zip'
      Role: !GetAtt LambdaRole.Arn
      FunctionName: !Sub '${AWS::StackName}-train'
  PredictLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: 'Predicts based existing ML model'
      Handler: predict.lambda_handler
      CodeUri: 's3://ml-engineer/cloudformation/lambda_templates/predict.zip'
      Role: !GetAtt LambdaRole.Arn
      FunctionName: !Sub '${AWS::StackName}-predict'
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub '${AWS::StackName}'
      Tags:
        - Key: project
          Value: ml-engineer
  PredictApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Body:
        swagger: "2.0"
        info:
          title: !Ref AWS::StackName
        basePath: "/dev"
        schemes:
          - "https"
        paths:
          /:
            get:
              produces:
                - "application/json"
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/Empty"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${PredictLambda}/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                contentHandling: "CONVERT_TO_TEXT"
                type: "aws_proxy"
        definitions:
          Empty:
            type: "object"
            title: "Empty Schema"
  PredictApiInvokePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PredictLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PredictApi}/*/*/*'
